Vagrant.configure("2") do |config|
  config.vm.hostname="control-node"
  config.vm.box="jasonc/centos7"
  config.vm.network "private_network", ip: "192.168.57.2"
  config.vm.synced_folder "../../src/", "/vagrant", type:"nfs"
end

