Vagrant.configure("2") do |config|
  config.vm.hostname="db01"
  config.vm.box="jasonc/centos7"
  config.vm.synced_folder "../../src/", "/vagrant", type: "rsync", rsync__exclude: ".git/" 
  config.vm.network "private_network", ip: "192.168.57.4"
  config.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip:"127.0.0.1"
end

