Vagrant.configure("2") do |config|
  config.vm.hostname="app01"
  config.vm.box="jasonc/centos7"
  config.vm.synced_folder "../../src/", "/vagrant", type: "nfs" 
  config.vm.network "private_network", ip: "192.168.57.3"
  config.vm.network "forwarded_port", guest: 8080, host: 18080, host_ip:"127.0.0.1"
  config.vm.provision "shell", path: "app01.sh"

end

